### ISSUE TITLE
add poetry.lock back

### ISSUE THREAD

**Issue by vladdu** [pawamoy/dependenpy#49]
**Describe the bug**
The poetry-lock file should be committed to version control, so that all contributors use the same versions.

I have cloned the repo, followed the instructions, but "make check" crashes due to some version mismatch.

**System (please complete the following information):**
- `Dependenpy` version: 3.3.0
- Python version: 3.8
- OS: Linux

**Comment by pawamoy** [comment]
I disagree, lock files should not be versioned for library/non-end-user projects. I prefer seeing CI break from time to time rather than resolving lock file conflicts / adding noise in PRs. I'll close but we can continue the discussion of course.
