### ISSUE TITLE
No module named 'mkdocstrings.handlers.python'

### ISSUE THREAD

**Issue by vladdu** [pawamoy/dependenpy#52]
**Describe the bug**
When running "make check", I get this error:

```
  > mkdocs build -s
  INFO     -  Cleaning site directory
  INFO     -  Building documentation to directory:
              /home/vdumitre/projects/dependenpy/site
  Package(s) not found: atomicwrites, cached-property, typed-ast
  INFO     -  The following pages exist in the docs directory, but are not
              included in the "nav" configuration:
                - usage.md
  ERROR    -  Error reading page 'reference/__init__.md': No module named
              'mkdocstrings.handlers.python'
```

**To Reproduce**
1. Run `make check`
2. See error

**System (please complete the following information):**
- `Dependenpy` version: 3.3.1.dev11
- Python version: 3.8
- OS: Linux

**Comment by pawamoy** [comment]
I've updated the project, this should be fixed.

The project now uses PDM instead of Poetry. The make commands are the same.
