### ISSUE TITLE
import a.b.c.d as utils is not counted

### ISSUE THREAD

**Issue by vdaele** [Pawamoy/dependenpy#9]
I have two modules
- a.b
- a.x
Within submodule a.x.y.z, there is an "import a.b.c.d as utils"

Hence I would expect a "uses' relation in the matrix.
However, "MatrixBuilder(['a.b','a.x']).build().get_matrix(2)" returns all zeros

Changing the import to eg "from a.b.c import d as utils" works fine

**Comment by Pawamoy** [comment]
In fact only the "from X import Y [as Z]" statements are handled. I will try to add the ability to handle "import" statements as well as soon as possible.

**Comment by Pawamoy** [comment]
Fixed in version 3!

Expect it to be released on PyPI soon.
